MxOnline/urls.py
# coding=utf-8
"""MxOnline URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url, include
from django.contrib import admin
import xadmin
from django.views.generic import TemplateView
from users.views import LoginView,RegisterView,ActiveUserView,ForgetPwView,ResetPwView,ModifyPwView,LogoutView,IndexView
from organization.views import OrgView
from django.views.static import serve
from django.conf import settings
urlpatterns = [
    # url(r'^static/(?P<path>.*)$', serve, {"document_root": settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$',IndexView.as_view(),name="index"),
    url('^login/$', LoginView.as_view(), name='login'),
    url('^logout/$', LogoutView.as_view(), name='logout'),
    url('^register/$', RegisterView.as_view(), name='register'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)$', ActiveUserView.as_view(), name='active_user'),
    url(r'^forget/$', ForgetPwView.as_view(), name='forget_pwd'),
    url(r'^forgetpw/(?P<forget_code>.*)$', ResetPwView.as_view(), name='reset_pw'),
    url(r'^modifypw/$', ModifyPwView.as_view(), name='modify_pw'),
    url(r'^org/', include('organization.urls', namespace='org')),
    url(r'^operation/', include('operation.urls', namespace='operation')),
    url(r'^course/', include('courses.urls', namespace='course')),
    url(r'^users/', include('users.urls', namespace='users')),
]
# 全局配置404页面
handler404 = "users.views.page_not_find"
handler500 = "users.views.page_error"

apps/courses/urls.py
from django.conf.urls import url

from .views import CourseListView,CourseDetailView,CourseInfoView,CommentsView,AddCommentsView,VideoPlayView

urlpatterns = [
    url(r'^list/$', CourseListView.as_view(), name='courses_list'),
    url(r'^detail/(?P<course_id>\d+)$', CourseDetailView.as_view(), name='courses_detail'),
    url(r'^info/(?P<course_id>\d+)$', CourseInfoView.as_view(), name='courses_info'),
    url(r'^comment/(?P<course_id>\d+)$', CommentsView.as_view(), name='courses_comment'),
    url(r'^add_comment/$', AddCommentsView.as_view(), name='add_comment'),
    url(r'^video/(?P<video_id>\d+)$', VideoPlayView.as_view(), name='video_play'),
]

apps/organization/urls.py
# -*- coding:utf-8 -*-
__author__ = "lsj"
__date__ = '2018/5/13/013 20:20'
from django.conf.urls import url
from .views import OrgView,AddUserAskView,OrgHomeView,OrgCourseView,OrgDescView,OrgTeacherView,TeacherListView,TeacherDetailView

urlpatterns = [
    url(r'^teacher/list/$', TeacherListView.as_view(), name='teacher_list'),
    url(r'^list/$', OrgView.as_view(), name='list'),
    url(r'^add_ask/$', AddUserAskView.as_view(), name='add_ask'),
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name='home'),
    url(r'^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name='course'),
    url(r'^desc/(?P<org_id>\d+)/$', OrgDescView.as_view(), name='desc'),
    url(r'^org_teacher/(?P<org_id>\d+)/$', OrgTeacherView.as_view(), name='org_teacher'),
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name='teacher_detail'),

]

apps/users/urls.py
# -*- coding:utf-8 -*-
__author__ = "lsj"
__date__ = '2018/5/19/019 21:17'

from django.conf.urls import url
from .views import UserInfoView,UpdateImageView,UpdatePwdView,SendEmailCodeView,UpdateEmailView,MyCourseView,MyFavOrgView
from .views import MyMessageView,MyFavTeacherView,MyFavCourseView

urlpatterns = [
    # 用户信息
    url(r'^info/$', UserInfoView.as_view(), name='user_info'),

    # 用户上传头像
    url(r'^image/upload/$', UpdateImageView.as_view(), name='user_upload'),

    # 用户个人中心修改密码
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name='update_pwd'),

    # 向邮箱里面发送验证码
    url(r'^sendemail_code/$', SendEmailCodeView.as_view(), name='sendemail_code'),

    # 修改邮箱
    url(r'^update_email/$', UpdateEmailView.as_view(), name='update_email'),

    # 我的课程
    url(r'^mycourse/$', MyCourseView.as_view(), name='mycourse'),

    # 我的收藏 机构
    url(r'^myfav/org$', MyFavOrgView.as_view(), name='myfav_org'),

    # 我的收藏讲师
    url(r'^myfav/teacher', MyFavTeacherView.as_view(), name='myfav_teacher'),

    # 我的收藏课程
    url(r'^myfav/course', MyFavCourseView.as_view(), name='myfav_course'),

    # 我的消息
    url(r'^mymessage', MyMessageView.as_view(), name='mymessage'),

]

apps/courses/models.py
# encoding:utf-8
from __future__ import unicode_literals
from datetime import datetime
from organization.models import CourseOrg,Teacher

from django.db import models

class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg,null=True,verbose_name=u"课程机构")
    name = models.CharField(max_length=50,verbose_name=u"课程名")
    desc = models.CharField(max_length=300,verbose_name=u"课程描述")
    teacher = models.ForeignKey(Teacher,null=True, verbose_name=u"讲师")
    detail = models.TextField(verbose_name=u"课程详情")
    is_banner = models.BooleanField(default=False,verbose_name=u"是否轮播")
    degree = models.CharField(choices=(("cj","初级"),("zj","中级"),("gz","高级")),max_length=2,verbose_name=u"难度")
    learn_time = models.IntegerField(default=0,verbose_name=u"学习时长（分钟）")
    students = models.IntegerField(default=0,verbose_name=u"学习人数")
    fav_nums = models.IntegerField(verbose_name=u"收藏人数", default=0)
    image = models.ImageField(verbose_name=u"封面图", upload_to='courses/%Y/%m', max_length=100)
    click_nums = models.IntegerField(verbose_name=u"点击数", default=0)
    category = models.CharField(verbose_name=u"课程类别",max_length=20,default="后端开发")
    tag = models.CharField(default="", verbose_name=u"课程标签", max_length=10)
    youneed_know = models.CharField(max_length=300,default="",verbose_name=u"课程须知")
    teacher_tell = models.CharField(max_length=200,default="",verbose_name=u"老师告诉你")
    add_time = models.DateTimeField(verbose_name=u"添加时间", default=datetime.now)
    class Meta:
        verbose_name = u'课程'
        verbose_name_plural = verbose_name

    # 获取课程所有章节
    def get_learn_lesson(self):
        return self.lesson_set.all()

    # 获取章节数量
    def get_zj_nums(self):
        return self.lesson_set.all().count()

    def get_learn_users(self):
        return self.usercourse_set.all()[:5]

    def __unicode__(self):
        return self.name

class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name=u"课程")
    name = models.CharField(verbose_name=u"章节名", max_length=100)
    add_time = models.DateTimeField(verbose_name=u"添加时间", default=datetime.now)

    class Meta:
        verbose_name = u'章节'
        verbose_name_plural = verbose_name

    # 获取章节视频
    def get_learn_video(self):
        return self.video_set.all()

    def __unicode__(self):
        return self.name


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name=u"章节名")
    name = models.CharField(verbose_name=u"视频名", max_length=100)
    url = models.CharField(verbose_name=u"访问地址",default="", max_length=200)
    learn_time = models.IntegerField(default=0, verbose_name=u"学习时长（分钟）")
    add_time = models.DateTimeField(verbose_name=u"添加时间", default=datetime.now)

    class Meta:
        verbose_name = u'视频'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name=u"课程")
    name = models.CharField(verbose_name=u"资源名", max_length=100)
    download = models.FileField(verbose_name=u"资源地址", upload_to='course/resource/%Y/%m', max_length=100)
    add_time = models.DateTimeField(verbose_name=u"添加时间", default=datetime.now)

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name


    def __unicode__(self):
        return self.name

templates/header-top.html
<div class="top">
    <div class="wp">
        <div class="fl"><p>服务电话：<b>33333333</b></p></div>
        <!--登录后跳转-->
        {% if request.user.is_authenticated %}
            <div class="personal">
                <dl class="user fr">
                    <dd>{{ request.user.username }}<img class="down fr" src="/static/images/top_down.png"/></dd>
                    <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                    </dt>
                </dl>
                <div class="userdetail">
                    <dl>
                        <dt><img width="80" height="80"
                                 src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                        </dt>
                        <dd>
                            <h2>{{ request.user.nick_name }}</h2>
                            <p>{{ request.user.username }}</p>
                        </dd>
                    </dl>
                    <div class="btn">
                        <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
                        <a class="fr" href="{% url "logout" %}">退出</a>
                    </div>
                </div>
            </div>
        {% else %}
            <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
            <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
        {% endif %}
        <a href="{% url "users:mymessage" %}">
            <div class="msg-num"><span id="MsgNum">{{ request.user.unread_nums }}</span></div>
        </a>
    </div>
</div>

templates/index.html
{% extends 'base.html' %}
{% block title %}
    公开课列表页
{% endblock %}

{% block bread %}

{% endblock %}

{% block content %}
    <div class="banner">
        <div class="wp">
            <div class="fl">
                <div class="imgslide">
                    <ul class="imgs">
                        {% for banner in all_banners %}
                            <li>
                                <a href="{{ banner.url }}">
                                    <img width="1200" height="478"
                                         src="{{ MEDIA_URL }}{{ banner.image }}"/>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>

        </div>


    </div>
    <!--banner end-->
    <!--feature start-->
    <section>
        <div class="wp">
            <ul class="feature">
                <li class="feature1">
                    <img class="pic" src="/static/images/feature1.png"/>
                    <p class="center">专业权威</p>
                </li>
                <li class="feature2">
                    <img class="pic" src="/static/images/feature2.png"/>
                    <p class="center">课程最新</p>
                </li>
                <li class="feature3">
                    <img class="pic" src="/static/images/feature3.png"/>
                    <p class="center">名师授课</p>
                </li>
                <li class="feature4">
                    <img class="pic" src="/static/images/feature4.png"/>
                    <p class="center">数据真实</p>
                </li>
            </ul>
        </div>
    </section>
    <!--feature end-->
    <!--module1 start-->
    <section>
        <div class="module">
            <div class="wp">
                <h1>公开课程</h1>
                <div class="module1 eachmod">
                    <div class="module1_1 left">
                        <img width="228" height="614" src="/static/images/module1_1.jpg"/>
                        <p class="fisrt_word">名师授课<br/>专业权威</p>
                        <a class="more" href="{% url "course:courses_list" %}">查看更多课程 ></a>
                    </div>
                    <div class="right group_list">
                        <div class="module1_2 box">
                            <div class="imgslide2">
                                <ul class="imgs">
                                    {% for course in banner_courses %}
                                        <li>
                                            <a href="{% url "course:courses_detail" course.id %}">
                                                <img width="470" height="300"
                                                     src="{{ MEDIA_URL }}{{ course.image }}"/>
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="unslider-arrow2 prev"></div>
                            <div class="unslider-arrow2 next"></div>
                        </div>
                        {% for course in courses %}
                            <div class="module1_{{ forloop.counter|add:2 }} box">
                                <a href="{% url "course:courses_detail" course.id %}">
                                    <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="course-detail.html">
                                        <h2 title="{{ course.name }}">{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl"
                                          title="{{ course.course_org.name }}">{{ course.course_org.name }}</span>
                                    <span class="star fr">{{ course.fav_nums }}</span>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="module greybg">
            <div class="wp">
                <h1>课程机构</h1>
                <div class="module3 eachmod">
                    <div class="module3_1 left">
                        <img width="228" height="463" src="/static/images/module3_1.jpg"/>
                        <p class="fisrt_word">名校来袭<br/>权威认证</p>
                        <a class="more" href="{% url "org:list" %}">查看更多机构 ></a>
                    </div>
                    <div class="right">
                        <ul>
                            {% for org in course_orgs %}
                                <li class="{% if forloop.counter|divisibleby:'5' %}five{% endif %}">
                                    <a href="{% url "org:home" org.id %}">
                                        <div class="company">
                                            <img width="184" height="100" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                            <div class="score">
                                                <div class="circle">
                                                    <h2>{{ org.tag }}</h2>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span class="key" title="{{ org.name }}">{{ org.name }}</span></p>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="/static/js/index.js"></script>
{% endblock %}

templates/org-list.html
{% extends 'base.html' %}
{% block title %}
    D慕学-机构列表页
{% endblock %}

{% block bread %}
    <li><a href="{% url 'org:list' %}">课程机构</a></li>
{% endblock %}

{% block content %}
    <section>
        <div class="wp butler_list_box list">
            <div class='left'>
                <div class="listoptions">
                    <ul>
                        <li>
                            <h2>机构类别</h2>
                            <div class="cont">
                                <a href="?city={{ city_id }}"><span class="{% ifequal category '' %}active2{% endifequal %}">全部</span></a>

                                <a href="?ct=pxjg&city={{ city_id }}"><span class="{% ifequal category 'pxjg' %}active2{% endifequal %}">培训机构</span></a>

                                <a href="?ct=gx&city={{ city_id }}"><span class="{% ifequal category 'gx' %}active2{% endifequal %}">高校</span></a>

                                <a href="?ct=gr&city={{ city_id }}"><span class="{% ifequal category 'gr' %}active2{% endifequal %}">个人</span></a>

                            </div>
                        </li>
                        <li>
                            <h2>所在地区</h2>
                            <div class="more">更多</div>
                            <div class="cont">
                                <a href="?ct={{ category }}"><span class="{% if not city_id %}active2{% endif %}">全部</span></a>
                                {% for city in cities %}
                                    <a href="?city={{ city.id }}&ct={{ category }}"><span class="{% ifequal city_id city.id %}
                                        active2
                                    {% endifequal %}
                                    ">{{ city.name }}</span></a>
                                {% endfor %}
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="all">共<span class="key">{{ orgs_count }}</span>家</div>
                <div class="butler_list company list">
                    <div class="layout">
                        <div class="head">
                            <ul class="tab_header">
                                <li class="{% if sort == '' %}active{% endif %}"><a href="?ct={{ category }}&city={{ city_id }}">全部</a></li>
                                <li class="{% if sort == 'students' %}active{% endif %}"><a href="?sort=students&ct={{ category }}&city={{ city_id }}">学习人数 &#8595;</a></li>
                                <li class="{% if sort == 'courses' %}active{% endif %}"><a href="?sort=courses&ct={{ category }}&city={{ city_id }}">课程数 &#8595;</a></li>
                            </ul>
                        </div>

                        {% for org in p_orgs.object_list %}
                            <dl class="des difdes">
                                <dt>
                                    <a href="{% url 'org:home' org.id %}">
                                        <img width="200" height="120" class="scrollLoading"

                                             data-url="{{ MEDIA_URL }}{{ org.image }}"/>
                                    </a>
                                </dt>
                                <dd>
                                    <div class="clearfix">
                                        <a href="">
                                            <h1>{{ org.name }}</h1>
                                            <div class="pic fl">

                                                <img src="/static/images/authentication.png"/>

                                                <img src="/static/images/gold.png"/>

                                            </div>
                                        </a>
                                    </div>
                                    <ul class="cont">
                                        <li class="first"><p class="pic9">课程数：<span>1</span></p>
                                            <p class="c7">学习人数：<span>1000</span></p></li>
                                        <li class="c8" style="padding-left:18px;">{{ org.address }}</li>
                                        <li class="pic10" style="padding-left:18px;">经典课程：

                                            <a href="/diary/19/">c语言基础入门</a>

                                            <a href="/diary/16/">数据库基础</a>

                                        </li>
                                    </ul>
                                </dd>
                                <div class="buy start_groupbuy jsShowPerfect2" data-id="22"><br/>联系<br/>服务</div>
                            </dl>
                        {% endfor %}

                    </div>
                    <div class="pageturn">
                        <ul class="pagelist">
                            {# 配置前一页 #}
                            {% if p_orgs.has_previous %}
                                <li class="long"><a href="?{{ p_orgs.previous_page_number.querystring }}">上一页</a></li>
                            {% else %}
                            {% endif %}
                            {# 配置中间内容 #}
                            {% for page in p_orgs.pages %}
                                {% if page %}
                                    {% ifequal page p_orgs.number %}
                                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                    {% else %}
                                        <li><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                    {% endifequal %}
                                {% else %}
                                {% endif %}
                            {% endfor %}
                            {# 配置下一页 #}
                            {% if p_orgs.has_next %}
                                <li class="long"><a href="?{{ p_orgs.next_page_number.querystring }}">下一页</a></li>
                            {% else %}
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="right companyright">
                <div class="head">我要学习</div>
                <form class="rightform" id="jsStayForm">
                    <div>
                        <img src="/static/images/rightform1.png"/>
                        <input type="text" name="name" id="companyName" placeholder="名字" maxlength="25"/>
                    </div>
                    <div>
                        <img src="/static/images/rightform2.png"/>
                        <input type="text" name="mobile" id="companyMobile" placeholder="联系电话"/>
                    </div>
                    <div>
                        <img src="/static/images/rightform3.png"/>
                        <input type="text" name="course_name" id="companyAddress" placeholder="课程名" maxlength="50"/>
                    </div>
                    <p class="error company-tips" id="jsCompanyTips"></p>
                    <input class="btn" type="text" id="jsStayBtn" value="立即咨询 >"/>
                    {% csrf_token %}
                </form>
            </div>

            <div class="right companyrank layout">
                <div class="head">授课机构排名</div>
                {% for current_org in hot_orgs %}
                     <dl class="des">
                        <dt class="num fl">{{ forloop.counter }}</dt>
                        <dd>
                            <a href="/company/2/"><h1>{{ current_org.name }}</h1></a>
                            <p>{{ current_org.address }}</p>
                        </dd>
                    </dl>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

{% block js %}
    <script>
        $(function () {
            $('#jsStayBtn').on('click', function () {
                $.ajax({
                    type: "POST",
                    url: "{% url "org:add_ask" %}",
                    data: $('#jsStayForm').serialize(),
                    success: function (data) {
                        if (data.status === 'success') {
                            $('#jsStayForm')[0].reset();
                            alert("提交成功")
                        } else if (data.status === 'fail') {
                            $('#jsCompanyTips').html(data.msg)
                        }
                    },
                    error:function (data) {

                    }
                });
            });
        })

    </script>
{% endblock %}

templates/reset_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>邮箱验证失败</h1>
</body>
</html>

templates/usercenter-fav-course.html
{% extends 'usercenter_base.html' %}

{% block title %}
    我的收藏- 慕学在线网
{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="/user/home/">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>
        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li><a href="{% url 'users:myfav_org' %}">课程机构</a></li>
                    <li><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                    <li class="active"><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                </ul>
            </div>
            <div class="companycenter">
                <div class="group_list brief">
                    {% for course in course_list %}
                         <div class="module1_5 box">
                        <a href="{% url 'course:courses_detail' course.id %}">
                            <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                        </a>
                        <div class="des">
                            <a href="{% url 'course:courses_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                            <span class="fl">时长：<i class="key">{{ course.learn_time }}</i></span>
                            <span class="fr">学习人数：{{ course.students }}</span>
                        </div>
                        <div class="bottom">
                            <span class="fl">{{ course.course_org.name }}</span>
                            <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/usercenter-fav-org.html
{% extends 'usercenter_base.html' %}

{% block title %}
    我的收藏- 慕学在线网
{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="/user/home/">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>

        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li class="active"><a href="{% url 'users:myfav_org' %}">课程机构</a></li>
                    <li><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                   <li><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                </ul>
            </div>
            <div class="messagelist">
                {% for org in org_list %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'org:home' org.id %}">
                                    <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'org:home' org.id %}">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">
                                    <img src="/static/images/authentication.png"/>
                                    <img src="/static/images/gold.png"/>
                                </div>
                                <span class="c8 clear">{{ org.address }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/usercenter-mycourse.html
{% extends 'usercenter_base.html' %}

{% block title %}
    我的课程- 慕学在线网
{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="/user/home/">个人中心</a>></li>
                <li>我的课程</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
        <div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的课程</h1>
			</div>
		</div>
		<div class="personal_des permessage">
			<div class="companycenter">
				<div class="group_list brief">
                    {% for user_course in user_courses %}
                       <div class="module1_5 box">
                            <a href="{% url 'course:courses_detail' user_course.course.id %}">
                                <img width="214" height="190" class="scrollLoading" src="{{ MEDIA_URL }}{{ user_course.course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:courses_detail' user_course.course.id %}"><h2>{{ user_course.course.name }}</h2></a>
                                <span class="fl">课时：<i class="key">{{ user_course.course.learn_time }}</i></span>
                                <span class="fr">学习人数：{{ user_course.course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ user_course.course.course_org.name }}</span>
                                <span class="star fr  notlogin" data-favid="15">{{ user_course.course.course_org.fav_nums }}</span>
                            </div>
                        </div>
                    {% endfor %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}